name: Build and Deploy to ECR

on:
  push:
    branches:
      - main  # Trigger only on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update to your region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo ${{ github.sha }})
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Start CodeBuild project
        run: |
          aws codebuild start-build --project-name YourCodeBuildProjectName \
            --environment-variables-override name=IMAGE_TAG,value=${{ env.IMAGE_TAG }}